### ISSUE TITLE
 'practnlptools\hash\depParse.sh': doesn't exist or not a regular file

### ISSUE THREAD

**Issue by danielvasic** [biplab-iitb/practNLPTools#3]
Hello I'm trying to install practnlptools on Windows I get  'practnlptools\hash\depParse.sh': doesn't exist or not a regular file, as far I can see depParse.sh is inside practnlptools folder?

**Comment by NeverInAsh** [comment]
same problem

**Comment by fedesire** [comment]
I first installed practnlptools in python3.6 and I got this problem,later I found it should be installed  in python2 enviroment,I did it then no problem comes up,so I guess this may be the solution
